### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by Unknownprok** [thiagola92/autocomplete-unity#1]
The package crash when using it offline

**Comment by thiagola92** [comment]
Now *autocomplete-unity* will download the API and save on computer. This way you can use it offline.  
**Note**: Each Unity API can take from 2.81 to 3.39 MB.

**Comment by thiagola92** [comment]
**Patch**:  

Saving the API directory inside **user project** -> Saving the API directory inside **autocomplete-unity package**  

I was accidentally creating the API directory inside the user project, sorry.  
You should check every project that you opened with Atom to remove this 'data' directory.

**Comment by Unknownprok** [comment]
U remind me of VS Code .vs inside every project😂
BTW u should add more auto completions for functions names(OnTrigerEnter,.....)
I am using ur package for school projects
Thanks for your work.

**Comment by thiagola92** [comment]
Thanks for using this package, tell me if you have any problem!

> BTW u should add more auto completions for functions names(OnTrigerEnter,.....)

Right now, i am just saving static methods/properties because i don't know how to identify the object i am inside. For example, i just want to recommend MonoBehaviour functions inside MonoBehaviour objects.  
I want to be able to do that without affecting performance too much :sob: .
